#!/command/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

setcap 'cap_net_raw+ep' /usr/local/bin/ping_exporter || true

### Execute Ping Exporter ###
exec s6-setuidgid icmpulse /usr/local/bin/ping_exporter --config.path=/var/run/icmpulse/config.yaml "${@}"
