ping:
  interval: {{ getenv "ICMPULSE_PING_INTERVAL" "10s" | quote }}
  timeout: {{ getenv "ICMPULSE_PING_TIMEOUT" "5s" | quote }}
  payload-size: {{ getenv "ICMPULSE_PING_SIZE" "56" }}
  history-size: {{ getenv "ICMPULSE_PING_HISTORY_SIZE" "20" }}

dns:
  refresh: {{ getenv "ICMPULSE_DNS_REFRESH" "5m" | quote}}

metrics:
  deprecated: disabled
  rttunit: s

targets:
  {{- range $i, $target := .targets }}
  {{- if not $target.labels }}
  - {{ $target.address }}
  {{- else }}
  - {{ $target.address }}:
    {{- range $key, $value := $target.labels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  {{- end }}
