##
# Copyright (C) 2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "ZXC: Build ICMPulse Exporter Images"
on:
  workflow_call:
    inputs:
      ## The tag version to be used
      tag-version:
        description: "Tag Version:"
        type: string
        required: true

      base-os-image:
        description: "Operating System Image:"
        type: string
        required: false
        default: "bookworm-20250811-slim"

      ## Linux Architectures for Multi-Arch Builds
      platforms:
        description: "Platforms:"
        type: string
        required: false
        default: "linux/amd64,linux/arm64"

      dry-run-enabled:
        description: "Perform Dry Run"
        type: boolean
        required: false
        default: false

      custom-job-label:
        description: "Custom Job Label:"
        type: string
        required: false
        default: "Build"

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-httpd-oidc-images:
    name: ${{ inputs.custom-job-label || 'Build' }}
    runs-on: swirldslabs-infrastructure-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup QEmu Support
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Setup Docker Buildx Support
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          version: v0.16.2
          driver-opts: network=host

      - name: Show Docker Version
        run: docker version

      - name: Show Docker Info
        run: docker info

      - name: Docker Login (Github)
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: ${{ inputs.dry-run-enabled != true }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Docker Registry
        id: registry
        run: |
          DOCKER_REGISTRY_PREFIX="ghcr.io/${{ github.repository }}"
          IMG_RESULT="push"
          
          if [[ "${{ inputs.dry-run-enabled }}" == "true" ]]; then
            DOCKER_REGISTRY_PREFIX="local"
            IMG_RESULT="cache"
          fi
          
          echo "prefix=${DOCKER_REGISTRY_PREFIX}" >>"${GITHUB_OUTPUT}"
          echo "operation=${IMG_RESULT}" >>"${GITHUB_OUTPUT}"

      - name: Calculate Source Date
        id: commit
        run: echo "source-date=$(git log -1 --pretty=%ct)" >> "${GITHUB_OUTPUT}"

      - name: Calculate Docker Tag
        id: docker-tag
        run: |
          TAG_VERSION="${{ inputs.tag-version }}"
          echo "version=${TAG_VERSION//+/-}" >>"${GITHUB_OUTPUT}"

      - name: Build Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ github.workspace }}/icmpulse-exporter
          platforms: ${{ inputs.platforms }}
          push: ${{ steps.registry.outputs.operation == 'push' }}
          load: ${{ steps.registry.outputs.operation == 'load' }}
          tags: |
            ${{ steps.registry.outputs.prefix }}/icmpulse-exporter:latest
            ${{ steps.registry.outputs.prefix }}/icmpulse-exporter:${{ steps.docker-tag.outputs.version }}
            ${{ steps.registry.outputs.prefix }}/icmpulse-exporter:${{ steps.docker-tag.outputs.version }}-${{ inputs.base-os-image }}
          build-args: |
            SOURCE_DATE_EPOCH=${{ steps.commit.outputs.source-date }}
            OS_VERSION_TAG=${{ inputs.base-os-image }}
